name = "template_name"
version = "1.0.0"
type = "text"
production_host = "lavender-louse-sheryl-gawl5bxe.bls.dev"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "template_name_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "template_name.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeig3ijgr6wlmhsw7wtic4y3y5iskdrkhw2z3h7g3ljze46tu7lvcxe"
created = "2025-03-30T16:22:00.135Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "e09d138c5d8540022a6d3fec8f64bc91abf5c4b51e95eeb1ce02eed7f9f7cd9f"
