name = "template_name"
version = "1.0.0"
type = "text"
production_host = "bronze-eagle-prudy-vpaqjrda.bls.dev"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "template_name_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "template_name.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeigfw4zu7u3ebhefb4tcobcexnj2t6wrb5m63wa3band4kbq7cx73m"
created = "2025-03-30T20:46:48.882Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "e9359fabc79cc1886aa66b8feaee190f5b993336da12852f940bf1178aaa5bfe"
